package soundwave.data;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Utility class providing helper methods for database operations.
 */
public final class DAOUtils {

    private DAOUtils() { }

    /**
     * Establishes a connection to a local MySQL database running on port 3306.
     *
     * @param database the database name.
     * @param username the database user.
     * @param password the database password.
     * @return a Connection to the specified database.
     */
    public static Connection localMySQLConnection(final String database, final String username, final String password) {
        try {
            final var host = "localhost";
            final var port = "3306";
            final var connectionString = "jdbc:mysql://" + host + ":" + port + "/" + database;
            return DriverManager.getConnection(connectionString, username, password);
        } catch (final SQLException e) {
            throw new DAOException(e);
        }
    }

    /**
     * Prepares a PreparedStatement with the given parameter values.
     *
     * @param connection the database connection.
     * @param query the SQL query string.
     * @param values the parameter values to set in the query.
     * @return the prepared statement ready for execution.
     * @throws SQLException if a database access error occurs.
     */
    public static PreparedStatement prepare(final Connection connection, final String query, final Object... values
    ) throws SQLException {
        PreparedStatement statement = null;
        try {
            statement = connection.prepareStatement(query);
            for (int i = 0; i < values.length; i++) {
                statement.setObject(i + 1, values[i]);
            }
            return statement;
        } catch (final SQLException e) {
            if (statement != null) {
                statement.close();
            }
            throw e;
        }
    }

    /**
     * Prepares a PreparedStatement with auto-generated keys retrieval.
     *
     * @param connection the database connection.
     * @param query the SQL query string.
     * @param autoGeneratedKeys flag indicating whether auto-generated keys should be returned.
     * @param values the parameter values to set in the query.
     * @return the prepared statement ready for execution.
     * @throws SQLException if a database access error occurs.
     */
    public static PreparedStatement prepareWithKeys(final Connection connection, final String query, final int autoGeneratedKeys, 
                                            final Object... values) throws SQLException {
        PreparedStatement statement = null;
        try {
            statement = connection.prepareStatement(query, autoGeneratedKeys);
            for (int i = 0; i < values.length; i++) {
                statement.setObject(i + 1, values[i]);
            }
            return statement;
        } catch (final SQLException e) {
            if (statement != null) {
                statement.close();
            }
            throw e;
        }
    }
}
